name: Run Unit Tests

on: [push]

jobs:
  tests:
    name: Unit Tests

    runs-on: ubuntu-latest

    env:
      DJANGO_ENV: github_actions

    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --three --dev
    - name: Analysing the code
      run: |
        pipenv run check_syntax
        # pipenv run check_style
    - name: Run migrations
      run: pipenv run ./manage.py migrate
    - name: Run Tests
      run: |
        pipenv run ./manage.py test
